// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD72Cf_JwqS_QVdvAZ2fmt5u0xrJHfs0BQ',
    appId: '1:382833184004:web:661000df17ec187f7c9451',
    messagingSenderId: '382833184004',
    projectId: 'bestwayquotes',
    authDomain: 'bestwayquotes.firebaseapp.com',
    storageBucket: 'bestwayquotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKXzPR4IBDx8CvOkSUJ-mZzX6BZ4mgEA',
    appId: '1:382833184004:android:33b6b58b9fe17d277c9451',
    messagingSenderId: '382833184004',
    projectId: 'bestwayquotes',
    storageBucket: 'bestwayquotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBh_uIaOtWqcp9kRUFNUrICcvP99x6s2A',
    appId: '1:382833184004:ios:d942900951ac82e27c9451',
    messagingSenderId: '382833184004',
    projectId: 'bestwayquotes',
    storageBucket: 'bestwayquotes.appspot.com',
    iosClientId: '382833184004-jcp5tq50ssgoa0a4q46j3bbo8jlsgboh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApiLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBh_uIaOtWqcp9kRUFNUrICcvP99x6s2A',
    appId: '1:382833184004:ios:d942900951ac82e27c9451',
    messagingSenderId: '382833184004',
    projectId: 'bestwayquotes',
    storageBucket: 'bestwayquotes.appspot.com',
    iosClientId: '382833184004-jcp5tq50ssgoa0a4q46j3bbo8jlsgboh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApiLogin',
  );
}
